name: Cypress Tests

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
  run-cypress-tests:
    runs-on: [ubuntu-latest]
    container: cypress/included:12.17.4
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        timeout-minutes: 30
        uses: cypress-io/github-action@v6.5.0
        with:
            browser: chrome

      - name: Archive Test Report (If Fails)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: |
            /cypress/screenshots/
            /cypress/videos/
          retention-days: 7
